include ./theme.conf
color_mode single
enable_gpu yes
background_image none

font_family JetBrainsMono Nerd Font
font_size 11.5
modify_font cell_height +6px
modify_font cell_width 106%

cursor_blink_interval 0
cursor_trail 1

show_hyperlink_targets yes
placement_strategy top

enable_audio_bell no

editor nvim

map ctrl+v paste_from_clipboard
map ctrl+c copy_or_noop
map ctrl+shift+o open_url_with_hints
